### ISSUE TITLE
RS256 alg does not work

### ISSUE THREAD

**Issue by danirukun** [fukamachi/jose#4]
## Example
```lisp
(jose:encode :rs256 (ironclad:ascii-string-to-byte-array "teststring") *payload*)
```
where `*payload*` is an alist of claims.

Calling this produces the following error:

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION IRONCLAD:DESTRUCTURE-PRIVATE-KEY (11)>
when called with arguments
  (#(116 101 115 116 115 116 114 105 110 103)).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
See also:
  Common Lisp Hyperspec, 7.6.6 [:section]
```

**Comment by fukamachi** [comment]
Confirmed. Seems something wrong with #1.

**Comment by fukamachi** [comment]
No, it's not.
RS256 is a method to encode with RSA crypt, so it requires a public key object instead of octets, unlike HS256.
Use an Ironclad public key object instead of `(ironclad:ascii-string-to-byte-array "teststring")`.

To create it from a file, https://github.com/fukamachi/asn1/ would help.

**Comment by danirukun** [comment]
Maybe it makes sense to add an example with a PEM file? Sorry it's just very hard to figure this out unless you have read the docs and source code of multiple libraries chained together in a specific way 😄 
RS256 is pretty common, and if `jose:encode` requires specific object types different from the README example, I fell like it should be documented.

**Comment by fukamachi** [comment]
That really makes sense. Even I had forgotten how to use it. :P

**Comment by fukamachi** [comment]
Done. Closing.
